#!/usr/bin/env zsh

# system
brew install gnu-sed --with-default-names

# PHP
brew install php71 \
	--with-homebrew-curl \
	--with-homebrew-libressl \
	--with-homebrew-libxml2 \
	--with-homebrew-libxslt \
	--without-apache \
	--without-fpm \
	--without-ldap \
	--without-legacy-mysql;

# PHP Conf
echo "date.timezone = 'Europe/Paris'" >> /usr/local/etc/php/7.1/php.ini
echo "phar.readonly = Off" >> /usr/local/etc/php/7.1/php.ini

if ! type 'composer' > /dev/null; then
  curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
else
  composer self-update --clean-backups
fi

composer global require friendsofphp/php-cs-fixer
composer global require phpmetrics/phpmetrics

# Python
pip install -U glances
pip install -U invoke

# Ruby
gem install jekyll
gem install middleman

# Node.js
npm install --global surge@latest
npm install --global webcoach@latest
npm install --global imageoptim-cli@latest

# apps
brew cask install onyx
brew cask install appcleaner
brew cask install gimp
brew cask install mkchromecast
brew cask install tunnelbear

