#!/usr/bin/env bash

#
# extra
#
brew tap kyoh86/tap
#
# tooling
#
brew install tmux
brew install jq
brew install yq
brew install asdf
brew install awscli
brew install aws-okta
brew install ffmpeg
brew install dnsmasq

brew install pgcli
brew install postgresql # gem install pg

#
# universe
#
brew install dep
brew install glide
brew install protobuf@3.1
brew install protobuf-c
brew install geos

brew tap kyoh86/tap
brew install richgo

#
# apps
#
brew cask install slack
brew cask install docker-edge
brew cask install google-chrome-canary
brew cask install firefox-developer-edition
brew cask install zoomus
brew cask install viscosity
brew cask install 1password
brew cask install spotify
brew cask install appcleaner
