#!/usr/bin/env bash

#
# tooling
#
brew install sublime-text

brew install tmux
brew install awscli
brew install ffmpeg

brew install pgcli
brew install libpq
brew install postgresql@15

brew install httpie
brew install grpcurl
brew install hadolint

brew install gh
brew install homeport/tap/dyff

#
# universe
#
asdf plugin add golang
asdf plugin add nodejs
asdf plugin add ruby
brew install libffi libyaml zlib readline
export RUBY_CONFIGURE_OPTS="--with-zlib-dir=/opt/homebrew/opt/zlib --with-openssl-dir=/opt/homebrew/opt/openssl@1.1 --with-readline-dir=/opt/homebrew/opt/readline --with-libyaml-dir=/opt/homebrew/opt/libyaml"
export RUBY_CFLAGS="-Wno-error=implicit-function-declaration"
export CONFIGURE_OPTS="--build aarch64-apple-darwin20"

brew install pre-commit

#
# apps
#
brew install sublime-text
brew install docker-desktop
brew install spotify
brew install nslogger
brew install gpg-suite
