#!/usr/bin/env zsh

#
# dependencies
#
brew install stow
brew install tmux
brew install jq
brew install awscli
brew install consul-template

brew cask install java
brew install scala
brew install sbt
brew install typesafe-activator

brew install mysql
brew install redis

brew install elixir

brew install slimerjs

yarn global add tslint

#
# apps
#
brew cask install 1password
brew cask install slack
brew cask install google-chrome-canary
