#!/usr/bin/env zsh

#
# tooling
#
brew install stow
brew install tmux
brew install jq
brew install rbenv

# languages
brew install python
brew install python@2

brew install --with-openssl --without-icu4c node8
npm install --global npm@5.8
npm install --global yarn

brew install --cask java8
brew install scala
brew install sbt

# addons
brew install mysql
brew install mycli

brew install redis

brew install postgresql
brew install pgcli

brew install elixir

brew install selenium-server-standalone
brew install chromedriver
brew install slimerjs

yarn global add typescript
yarn global add tslint
yarn global add imagemin-cli

brew install dnsmasq

#
# apps
#
brew install --cask docker-edge
brew install --cask 1password
brew install --cask slack
brew install --cask google-chrome-canary
brew install --cask firefoxdeveloperedition
brew install --cask chromium
brew install --cask imageoptim
brew install --cask zoom
brew install --cask sequel-pro
brew install --cask intellij-idea-ce
brew install --cask psequel

#
# Cloud
#
brew install kubectl
brew install awscli
brew install awslogs
brew install --cask aws-vault

brew install --cask google-cloud-sdk
gcloud components install docker-credential-gcr --quiet
