#!/usr/bin/env zsh

#
# dependencies
#
brew install stow
brew install tmux
brew install jq
brew install awscli
brew install terraform
brew install consul-template
brew install vault

brew cask install java
brew install scala
brew install sbt
brew install typesafe-activator

brew install mysql
brew install redis

brew install elixir

brew install slimerjs

yarn global add typescript
yarn global add tslint
yarn global add imagemin-cli

brew install docker

#
# apps
#
brew cask install virtualbox
brew cask install vagrant
brew cask install 1password
brew cask install slack
brew cask install google-chrome-canary
brew cask install chromium
brew cask install imageoptim
brew cask install aws-vault
brew cask install zoomus
