#!/usr/bin/env zsh

#
# exports
#


#
# dependencies
#

# PHP
brew install php70 --with-imap --with-postgresql --with-homebrew-curl --with-homebrew-libxml2 --with-homebrew-libxslt --without-apache --without-ldap;

# PHP Conf
echo "date.timezone = 'Europe/Paris'" >> /usr/local/etc/php/7.0/php.ini
echo "phar.readonly = Off" >> /usr/local/etc/php/7.0/php.ini

if ! type 'composer' > /dev/null; then
  curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
else
  composer self-update --clean-backups
fi

composer global require friendsofphp/php-cs-fixer
composer global require phpmetrics/phpmetrics

# Python
pip install -U glances
pip install -U invoke

# Ruby
gem install jekyll
gem install middleman

# Node.js
npm install --global surge@latest
npm install --global webcoach@latest
npm install --global imageoptim-cli@latest

# apps
brew cask install appcleaner
brew cask install brave
brew cask install gimp
brew cask install mkchromecast

